# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(default='ZFATVVFB', max_length=12, unique=True)),
                ('session_time', models.IntegerField(default=3600)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('successful', models.BooleanField()),
                ('ip', models.GenericIPAddressField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securecore.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('data_type', models.CharField(max_length=32)),
                ('downloads', models.IntegerField(default=0)),
                ('max_downloads', models.IntegerField(blank=True, default=None, null=True)),
                ('file', models.FileField(upload_to='uploads/clients/03b8d24b-a87c-4d58-b2d6-d47c4b2ffbce')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securecore.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('successful', models.BooleanField()),
                ('ip', models.GenericIPAddressField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securecore.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=256)),
                ('answer', models.CharField(max_length=256)),
                ('hint', models.CharField(max_length=256)),
                ('lowercase', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securecore.Client')),
            ],
        ),
        migrations.AddField(
            model_name='download',
            name='drop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securecore.Drop'),
        ),
        migrations.AddField(
            model_name='client',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='securecore.Provider'),
        ),
    ]
